site_name: OpenFOAM_CoSimIO-Adapter
site_description: Documentation for OpenFOAM Adapter
site_author: Duc Anh Truong

repo_name: juancamarotti/OpenFOAM_CoSimIO-Adapter
repo_url: https://github.com/juancamarotti/OpenFOAM_CoSimIO-Adapter
edit_uri: edit/main/docs/

theme:
  name: material

  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Overview: index.md

  - Get the adapter: get.md

  - Configuration: config.md

  - Extending: extend.md

  - OpenFOAM support: openfoam-support.md