name: Build with OpenFOAM v2512
on:
  push:
    branches-ignore:
      - 'OpenFOAM*'
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
  pull_request:
    branches-ignore:
      - 'OpenFOAM*'
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    container: precice/precice:nightly
    steps:
    - name: Check out repository
      uses: actions/checkout@v6
    - name: Set up OpenFOAM
      uses: gerlero/setup-openfoam@v1
      with:
        openfoam-version: 2512

    - name: Clone CoSimIO
      run: |
        git clone --depth 1 \
          https://github.com/KratosMultiphysics/CoSimIO.git \
          CoSimIO

    - name: Build CoSimIO
      run: |
        cmake \
          -S CoSimIO \
          -B CoSimIO/build \
          -DCO_SIM_IO_BUILD_MPI=ON \
          -DCO_SIM_IO_BUILD_TESTING=OFF

        cmake --build CoSimIO/build --parallel

    - name: Set CoSimIO environment
      run: |
        echo "COSIMIO_ROOT=$GITHUB_WORKSPACE/CoSimIO" >> "$GITHUB_ENV"
        echo "LD_LIBRARY_PATH=$GITHUB_WORKSPACE/CoSimIO/build:${LD_LIBRARY_PATH:-}" >> "$GITHUB_ENV"
    - name: Build OpenFOAM-CoSimIO adapter
      run: ./Allwmake
